### ISSUE TITLE
Feature request: pointcloud kinectgrabber

### ISSUE THREAD

**Issue by yiids** [d3cod3/ofxVisualProgramming#10]
Hi!
I was wondering if it would be to extend the functionality of the kinectgrabber. In the default openframeworks examples there is an example of kinect, where you can see and navigate in a point cloud, I think this is visually interesting and would like to have this inside of mosaic, maybe with the possibility of modifying the axis of the cam, zoom tilt etc. Maybe this is already possible using the objects in mosaic, but I haven't figured it out.
I have some experience in programming but am very new to mosaic, I thought maybe this could be something relatively easy to implement? 
If you could give me some pointers on how to implement this I surely will try ;)

**Comment by d3cod3** [comment]
Hi, nice request!

Yes, right now the kinect grabber object just give you access to the image ( standard or IR, you can switch it from the object ), and you can control far and near thresholds.

All the other stuff is to be implemented yet, you can check the current kinect grabber code here:

https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/objects/video/KinectGrabber.h
https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/objects/video/KinectGrabber.cpp

as you can see, the coding structure is OF based, so if you have experience with OF, it would be easy to modify just this particular object code and implement your suggestions.

I'll wait for your PR with the changes!

If you have any technical questions about the code, we can just use this issue.
