### ISSUE TITLE
Failure to compile examples

### ISSUE THREAD

**Issue by mwolfeu** [d3cod3/ofxVisualProgramming#11]
OFx: of_v0.11.2_linux64gcc6_release
Ubuntu: 20.04

Making either example yields:
myhomedir/of/addons/ofxVisualProgramming/example_ofxVisualProgramming/src/main.cpp:36:10: fatal error: ofxTimeMeasurements.h: No such file or directory
   36 | #include "ofxTimeMeasurements.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~

The file does not exist in the OFx directory.  

How best should I correct the problem?
Thanks!

**Comment by d3cod3** [comment]
Just fixed the issue with the last commit, just git pull again the repo and re-compile.
