### ISSUE TITLE
Segmentation fault on launch

### ISSUE THREAD

**Issue by baydam** [d3cod3/ofxVisualProgramming#2]
OS: Arch Linux
OF version: 0.10
GCC version: 8.2.1
After following all the compilation steps the visual programming sketch display "segmentation fault" on launch

**Comment by d3cod3** [comment]
Hi baydam, can you please attach some more info? I've tested it in various ubuntu and debian machines, but never on Arch Linux. It shouldn't be a problem but let's check the errors. Is compiling or it give you the segfault on launchig the app?

**Comment by baydam** [comment]
I finally solve this problem by removing ofxPoco in addon.make file of my project and addons_config.mk of ofxVisualProgramming.
Thanks

**Comment by d3cod3** [comment]
It's probably related with ofxPoco libs dependencies for newer linux (ubuntu 18.04, debian 9, etc), and it can be solved installing libpoco-dev in your system, and updating the poco include files inside ofxPoco addon. Check https://github.com/openframeworks/openFrameworks/commit/84077013d8a9c482696af18777a4e6976afe970c out for more info.
