### ISSUE TITLE
not an issue, not much related but... 

### ISSUE THREAD

**Issue by moebiussurfing** [d3cod3/ofxVisualProgramming#3]
What are you using or what can you recommends me to use to very simple node wire patching variables/to/targets? 
Something like 4 gui sliders that I what to choice as control/input for another 4 sliders. 
The tiny object I can use to this...
1---...........1
2.....\ ....... 2
3.......\---- 3
4.............  4
Not searched too much yet, so I am sorry If it's a lazy question...

**Comment by moebiussurfing** [comment]
could be some class on your datgui fork maybe?

**Comment by d3cod3** [comment]
Hi,
are you asking for c++ code or doing that with Mosaic?

**Comment by moebiussurfing** [comment]
I mean outside, in OF/c++. But a tiny patching module only without much
add-ons or block.
I am looking into ofxdarknigth too

**Comment by d3cod3** [comment]
Ok, well you can take a look at the base class for object i've written for ofxVisualProgramming, https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/PatchObject.h
&
https://github.com/d3cod3/ofxVisualProgramming/blob/master/src/PatchObject.cpp

In that class there is the core code for the patching modules
But i'm not going to lie, it's not an easy topic, if is too complicated maybe you can take a look at the addon i look up to in the beginning of the developing of ofxVisualProgramming:

https://github.com/patriciogonzalezvivo/ofxComposer

Is a little bit outdated, but the code is simpler.

Hope this will help you!

**Comment by d3cod3** [comment]
And by the way, you can always include ofxVisualProgramming in your project, and just load the specific objects you'll need, i mean hardcoding the calls and have a static preloaded objects environment.
